### ISSUE TITLE
Update the meeting table for last meeting  /Update-12

### ISSUE THREAD

**Issue by RDominguezFL** [JaxLUG/jaxlug.github.io#9]

**Comment by cavcrosby** [comment]
This meeting table would have to be updated after each meeting, which means a reoccurring GitHub issue would have to be @RD created to update it. Is there a better approach for this we could do?

**Comment by RDominguezFL** [comment]
so far i have not found one in the github documents.   How do you handle reoccurring that is not exact and can not be automated.   i said that because the blur about what when on is a recap of the meeting.  we can automate the date and table creation but the text of what when on can not.
